### ISSUE TITLE
Start state does not change according to current state

### ISSUE THREAD

**Issue by LordAbraham** [Dobot-Arm/CR_ROS#13]
Hi, I'm having an issue with this package on my CR5: the Robot works fine, it can be ordered to move via ROS, but state always remains in home position (all joints set to 0), so in result all moves are executed through this point.

My control cabinet model: CC161
Communication via LAN
rostopic command on joint states confirms that it is not stuck at one value, but it's repeatedly updating it to 0 on all joints.

Same issue as there: https://answers.ros.org/question/414002/start-state-does-not-change-according-to-current-state/

**Comment by LordAbraham** [comment]
Ok I found solution TCP/IP communication is decided in my case on two ports 30004 is for sending data and 30003 is for receiving but the ROS package was written to only use one for both purses (probably previous owner changed this configuration). So in my case, all what was to do is little change in CR_ROS/dobot_bringup/include/dobot_bringup/commander.h that adds port 30004 for receiving state data.

[commander.zip](https://github.com/Dobot-Arm/CR_ROS/files/11948921/commander.zip)

**Comment by iameijaz** [comment]
@LordAbraham  which Ubuntu version, and which branch did you clone. I am facing the same issue.
